[feat] Allows multi-tenant Flowbroker-UI
dojot/flowbroker-ui pull request #6
Opened 2021-11-05 18:11 UTC by cfrancisco

- This PR refactor the node-Red engine to allow managing multi-tenant operations.

[[To Reviewers]]
In order to facilitate the review process, all files mentioned in the first line:
/* === This is a file from Node-Red being used as-is. === */
The code has not been changed
I would recommend skipping them for now and prioritizing the files that were changed.

2021-11-22 13:25 UTC, luissajunior requested changes

2021-11-22 17:30 UTC, cfrancisco commented on README.md
> +- If a new tenant is created, we should restart the service;
Existe uma forma um pouco mais custosa, que seria conectar no kafka, ouvir a mensagem de novo usuario/tenant. E quando recebesse essa mensagem, eu faria a instanciação de um node-red.  Inicialmente não era o escopo da integração este ponto, mas posso ver com o César.

2021-11-22 17:33 UTC, cfrancisco commented on app/modules/dojot/StorageMediator.js
> +      await dojotHandler.init();
Ótimo ponto, eu acho que não deveria estar aqui... Vou verificar.

2021-11-22 17:34 UTC, cfrancisco commented on app/modules/dojot/utils.js
> +  const flowsElements = JSON.parse(JSON.stringify(auxiliarStorage));
Estou fazendo um deep clone do objeto.

2021-11-26 13:31 UTC, cfrancisco commented on app/modules/dojot/StorageMediator.js
> +      await dojotHandler.init();
Corrigido!

2021-11-30 16:58 UTC, luisfelipefurlan approved these changes

2021-11-30 17:03 UTC, luissajunior approved these changes

2021-12-01 13:40 UTC, merged